sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_script:
  - brew install redis
  - redis-server
  - brew install mongodb
  - mongod
  - npm install -g grunt-cli
  - npm install
script:
  - node app